[package]
name = "xapi-rs"
description = "A conformant LRS implementation of xAPI 2.0.0"
license.workspace = true
version = "0.3.1"
authors.workspace = true
edition.workspace = true
repository.workspace = true
keywords = ["xAPI", "LRS", "web", "server"]
categories = ["web-programming::http-server", "data-structures", "api-bindings", "wasm"]
include = [
    "/doc/**",
    "/migrations/**",
    "/plugins/**",
    "/src/**",
    "/tests/**",
    ".env.template",
    "Cargo.toml",
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md",
    "Rocket.toml.template"
]

[dependencies]
# xapi-data = { path = "../data" }
xapi-data = "1.0.0"
# xapi-interfaces = { path = "../interfaces" }
xapi-interfaces = "0.1.0"

# ----- common / workspace -----
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
iri-string = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

# ----- data -----
serde_with = { workspace = true }
mime = { workspace = true }

# ----- db -----
dotenvy = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
async-recursion = { workspace = true }
rand = { workspace = true }

# ----- lrs -----
tracing-subscriber = { workspace = true }
rocket = { workspace = true }
rocket-multipart = { workspace = true }
etag = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
dashmap = { workspace = true }
lru = { workspace = true }
openssl = { workspace = true }
josekit = { workspace = true }

wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }

[dev-dependencies]
test-context = { workspace = true }
tracing-test = { workspace = true }
