[package]
name = "xx-plugin"
description = "Hashing implementation using twox-hash"
version = "0.1.0"
keywords = ["xAPI", "WASM", "WASIp1", "Hashing", "Plugin"]
categories = ["wasm"]

authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# xapi-interfaces = { path = "../../interfaces" }
xapi-interfaces = "0.1.0"
twox-hash = { version = "2.1.4", default-features = false, features = ["xxhash32", "std"] }

[lib]
crate-type = ["cdylib"]
